name: rtcloud_av1
channels:
  - defaults
  - conda-forge
dependencies:
  - awscli
  - bcrypt
  - boto3
  - dcm2niix
  - flake8
  - indexed_gzip  # for efficient random access of gzipped files with Nibabel
  - jupyter
  - mypy
  - nibabel
  - nilearn
  - nodejs
  - numpy
  - pip
  - pydicom
  - pytest
  - python=3.7
  - requests
  - rpyc
  - scipy
  - toml
  - tornado
  - websocket-client
  - wsaccel # for websocket acceleration
  - brainiak::brainiak  # specifing the channel
  - nomkl
  - scikit-learn
  - pip:
    - inotify
    - pybids
    - watchdog
    - psychtoolbox
    - psychopy
    - phate
    - pillow
    - graphtools
    - imageio
    - imageio-ffmpeg
    - brainiak
    - javascripthon
    - json-tricks
    - pybids
    - pygame
    - pyglet
    - pygsp
    - questplus
    - scprep
    - seaborn
    - wxpython
