name: rtcloud_av
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - awscli=1.20.56
  - backcall=0.2.0
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - blas=1.0
  - bleach=4.0.0
  - botocore=1.21.56
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.9.30
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - colorama=0.4.3
  - cryptography=3.4.8
  - cycler=0.10.0
  - cython=0.29.24
  - dbus=1.13.18
  - dcm2niix=1.0.20210317
  - debugpy=1.4.1
  - defusedxml=0.7.1
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.4.1
  - flake8=3.9.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.21.0
  - glib=2.68.2
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=3.2.1
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - inflect=5.3.0
  - iniconfig=1.1.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.4
  - jedi=0.18.0
  - jinja2=3.0.1
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libclang=11.1.0
  - libedit=3.1.20210714
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libgpuarray=0.7.6
  - libiconv=1.16
  - libllvm11=11.1.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - llvm-meta=7.0.0
  - lz4-c=1.9.3
  - mako=1.1.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - more-itertools=8.8.0
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.3.2
  - munkres=1.1.4
  - mypy=0.910
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.2
  - nibabel=3.2.1
  - nilearn=0.8.1
  - nitime=0.9
  - nodejs=16.6.1
  - notebook=6.4.3
  - nspr=4.30
  - nss=3.67
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openmp=7.0.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.3
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.8.2
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - pluggy=0.13.1
  - plumbum=1.7.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pybind11=2.7.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pydicom=2.2.2
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pygpu=0.7.6
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qt=5.12.9
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - requests=2.26.0
  - rpyc=5.0.1
  - rsa=4.7.2
  - s3transfer=0.5.0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - terminado=0.9.4
  - testpath=0.5.0
  - theano=1.0.4
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - wsaccel=0.6.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - arabic-reshaper==2.1.3
    - astunparse==1.6.3
    - bids-validator==1.8.4
    - brainiak==0.11
    - click==8.0.1
    - decorator==4.4.2
    - deprecated==1.2.13
    - distro==1.6.0
    - docopt==0.6.2
    - dukpy==0.2.3
    - esprima==4.0.1
    - et-xmlfile==1.1.0
    - freetype-py==2.2.0
    - future==0.18.2
    - gevent==21.8.0
    - gitdb==4.0.9
    - gitpython==3.1.24
    - glfw==2.4.0
    - graphtools==1.5.2
    - greenlet==1.1.2
    - imageio==2.13.0
    - imageio-ffmpeg==0.4.5
    - inotify==0.2.10
    - javascripthon==0.11
    - json-tricks==3.15.5
    - macropy3==1.1.0b2
    - moviepy==1.0.3
    - msgpack==1.0.3
    - msgpack-numpy==0.4.7.1
    - nose==1.3.7
    - num2words==0.5.10
    - openpyxl==3.0.9
    - phate==1.0.7
    - pillow==8.4.0
    - proglog==0.1.9
    - psychopy==2021.2.3
    - psychtoolbox==3.0.18.0
    - pybids==0.13.2
    - pygame==2.1.0
    - pyglet==1.4.11
    - pygsp==0.5.1
    - pyo==1.0.4
    - pyopengl==3.1.5
    - pyparallel==0.2.2
    - pyserial==3.5
    - python-bidi==0.4.2
    - python-gitlab==2.10.1
    - python-vlc==3.0.12118
    - python-xlib==0.31
    - questplus==2019.4
    - requests-toolbelt==0.9.1
    - s-gd2==1.8
    - scprep==1.1.0
    - smmap==5.0.0
    - sounddevice==0.4.3
    - soundfile==0.10.3.post1
    - sqlalchemy==1.3.24
    - tables==3.6.1
    - tasklogger==1.1.0
    - tqdm==4.62.3
    - ujson==4.3.0
    - watchdog==2.1.6
    - wrapt==1.13.1
    - wxpython==4.0.4
    - xarray==0.20.1
    - xlrd==2.0.1
    - zope-event==4.5.0
    - zope-interface==5.4.0
