title = "Sample Project"
sessionId = "20180310T123000"
subjectName = "0219191_faceMatching"
datestr = 20190219
subjectNum = 101
subjectDay = 1
sessionNum = 1
runNum = [ 1,]
scanNum = [ 13,]
trInterval = 2
dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
minExpectedDicomSize = 300000
plotTitle = "Realtime Plot"
plotXLabel = "Sample #"
plotYLabel = "Value"
plotXRangeLow = 0
plotXRangeHigh = 20
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = true
