title = "Sample Project - Synthetic Data"
isSynthetic = true
numSynthetic = 200
sessionId = "20200101T120000"
subjectName = "001_synthetic"
datestr = 20200101
imgDir = "/tmp/synthetic_dicom"
subjectNum = 101
subjectDay = 1
sessionNum = 1
runNum = [ 1,]
scanNum = [ 13,]
plotTitle = "Realtime Plot"
plotXLabel = "Sample #"
plotYLabel = "Value"
plotXRangeLow = 0
plotXRangeHigh = 200
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = true
dicomNamePattern = "rt_{TR:03d}.dcm"
minExpectedDicomSize = 200000
