title = "avatarRT"
session = 1
subjectDay = 1
subjectName = "synth-sub"
LASTNAME = "avatarRT_synth"
subjectIDforxnat = "avatarRT_sub-000_ses-01"
YYYYMMDD = 20220927
preDay_YYYYMMDD = "0"
rtFolder_subjectName = "avatarRT_synth"
studyDescription = "avatarRT"
isSynthetic = 1
syntheticDataPath = "/gpfs/milgram/project/turk-browne/users/elb77/BCI/rt-cloud/projects/avatarRT/fmrisim/"
verbose = 1
TR = 1.5
num_total_TRs = 450
TrialNumber = 1
TempDir = "/gpfs/milgram/scratch60/turk-browne/elb77/REALTIME"
runNums = [ 1,]
runNum = [ 1,]
scanNum = [ 1,]
staircasedBrainConfidence = [ 1,]
minExpectedDicomSize = 100
dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
mask = "mask.nii.gz"
nVox = 100
plotTitle = "real time plot"
plotXLabel = "Sample #"
plotYLabel = "Value"
plotXRangeLow = 0
plotXRangeHigh = 450
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = false
game_mode = 1
difficulty = 0
noisy_level = true
UNITY_PORT = 4042
UNITY_WAIT_TIME = 30
USING_PSYCHOPY = 1
skip_TR_begin = 2
win_size = [ 400, 400,]
TR_discard = 0
end_buffer = 4
