title = "avatarRT"
session = 1
subjectDay = 1
subjectName = "sub-phantom_01"
LASTNAME = "phantom_01_ses_01"
subjectIDforxnat = "phantom_01_ses_01"
YYYYMMDD = 20221017
preDay_YYYYMMDD = "0"
rtFolder_subjectName = "phantom_01"
studyDescription = "avatarRT"
isSynthetic = 0
verbose = 1
TempDir = "/gpfs/milgram/scratch60/turk-browne/elb77/REALTIME/"
TR = 2
num_total_TRs = 450
TrialNumber = 1
runNums = [ 1,]
scanNum = [ 4,]
runNum = [ 1,]
staircasedBrainConfidence = [ 1,]
minExpectedDicomSize = 300000
dicomNamePattern = "002_{SCAN:06d}_{TR:06d}.dcm"
mask = "mask.nii.gz"
nVox = 100
plotTitle = "real time plot"
plotXLabel = "Sample #"
plotYLabel = "Value"
plotXRangeLow = 0
plotXRangeHigh = 450
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = false
game_mode = 1
difficulty = 0
noisy_level = true
UNITY_PORT = 4044
UNITY_WAIT_TIME = 30
USING_PSYCHOPY = 1
skip_TR_begin = 2
win_size = [ 400, 400,]
TR_discard = 0
end_buffer = 4
