title = "avatarRT"
session = 1
subjectDay = 1
subjectName = "sample-openneuro"
subjectNum = "01"
LASTNAME = "sample-openneuro_ses-01"
subjectIDforxnat = "sample-openneuro"
YYYYMMDD = 20221015
preDay_YYYYMMDD = "0"
rtFolder_subjectName = "sample-openneuro"
studyDescription = "avatarRT"
isSynthetic = 0
projInterfaceHost = "172.29.189.151"
projInterfacePort = 6664
TempDir = "/tmp/REALTIME_EB/"
taskName = "movie"
verbose = 1
TR = 2
num_total_TRs = 20
TrialNumber = 1
runNums = [ 1, 2, 3, 4,]
runNum = [ 1,]
scanNum = [ 1,]
staircasedBrainConfidence = 0.99
mask = "mask.nii.gz"
minExpectedDicomSize = 300000
dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
fwhm = 5
plotTitle = "real time plot"
plotXLabel = "Sample #"
plotYLabel = "Value"
plotXRangeLow = 0
plotXRangeHigh = 450
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = false
game_mode = 1
difficulty = 0
noisy_level = true
UNITY_PORT = 4044
UNITY_WAIT_TIME = 30
USING_PSYCHOPY = 1
skip_TR_begin = 2
win_size = [ 400, 400,]
TR_discard = 0
end_buffer = 4
demoStep = 2
dsAccessionNumber = "ds001545"
